p8105_hw2_yh3683
================
Yining He
2024-10-01

## Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
nyc_subway_data = read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
nyc_subway_data =janitor::clean_names(nyc_subway_data)

colnames(nyc_subway_data)
```

    ##  [1] "division"           "line"               "station_name"      
    ##  [4] "station_latitude"   "station_longitude"  "route1"            
    ##  [7] "route2"             "route3"             "route4"            
    ## [10] "route5"             "route6"             "route7"            
    ## [13] "route8"             "route9"             "route10"           
    ## [16] "route11"            "entrance_type"      "entry"             
    ## [19] "exit_only"          "vending"            "staffing"          
    ## [22] "staff_hours"        "ada"                "ada_notes"         
    ## [25] "free_crossover"     "north_south_street" "east_west_street"  
    ## [28] "corner"             "entrance_latitude"  "entrance_longitude"
    ## [31] "station_location"   "entrance_location"

``` r
cleaned_data <- nyc_subway_data %>%
  select(line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, entry, vending, entrance_type, ada) %>%
  mutate(
    entry = ifelse(entry == "YES", TRUE, FALSE)  
  )
```

``` r
view(cleaned_data)
```

#### Describe about the cleaned dataset:

**The dataset contains NYC subway station information, including line,
station name, latitude/longitude, routes(Route1-Route7), entry status,
vending, entrance type, and ADA compliance.**

**Data cleaning involved standardizing column names, selecting relevant
variables, and converting the entry variable to a logical TRUE/FALSE
format. The cleaned dataset has 1,868 rows and 15 columns, and with each
row representing a unique station entrance or exit.**

**But I don’t think is tidy enough, because it still have many missing
data (NA).**

``` r
distinct_stations <- cleaned_data %>% 
  distinct(station_name, line) 

n_distinct_stations <- nrow(distinct_stations)
n_distinct_stations
```

    ## [1] 465

**The number of distinct stations are 465**

``` r
ada_compliant_stations <- cleaned_data %>%
  filter(ada == TRUE) %>%
  distinct(station_name, line)

n_ada_compliant_stations <- nrow(ada_compliant_stations)

n_ada_compliant_stations
```

    ## [1] 84

**There are 84 ADA compliant stations.**

``` r
no_vending_entrances <- cleaned_data %>%
  filter(vending == "NO")

proportion_allowing_entrance <- mean(no_vending_entrances$entry)
proportion_allowing_entrance
```

    ## [1] 0.3770492

**The proportion of station entrances / exits without vending allow
entrance is about 37.70.**

#### reform the data

``` r
reformatted_data <- cleaned_data %>%
  pivot_longer(cols = starts_with("route"), 
               names_to = "route_number", 
               values_to = "route_name") %>%
  filter(!is.na(route_name)) 
```

#### the number of distinct stations that serve the A train

``` r
a_train_stations <- reformatted_data %>%
  filter(route_name == "A") %>%
  distinct(station_name, line)

n_a_train_stations <- nrow(a_train_stations)
n_a_train_stations
```

    ## [1] 60

**There are 60 distinct stations serve the A train**

``` r
# Filter for ADA-compliant stations that serve the A train
ada_a_train_stations <- reformatted_data %>%
  filter(route_name == "A", ada == TRUE) %>%
  distinct(station_name, line)

n_ada_a_train_stations <- nrow(ada_a_train_stations)

n_ada_a_train_stations
```

    ## [1] 17

**There are 17 stations that serve the A train are ADA compliant.**
